[workspace]
members = ["app", "database"]

[workspace.dependencies]
anyhow = "1.0"
database = { path = "./database" }
dotenvy = "0.15"
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls", "sqlite" ] }
tokio = { version = "1.36", features = ["full"] }
